<% require "dotenv"; Dotenv.load(".env") %>

service: linkboard
image: <%= ENV['REGISTRY_USERNAME'] %>/linkboard
servers:
  - <%= ENV['SERVER_IP'] %>

proxy:
  ssl: true
  host: <%= ENV['APP_DOMAIN'] %>
  healthcheck:
    path: /health

registry:
  server: ghcr.io
  username:
    - REGISTRY_USERNAME
  password:
    - REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

# TODO: add volume for sqlite db
# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"
